version: '2.1'
services:

  evm-mainnet:
    image: settler:latest
    container_name: evm-mainet
    volumes:
      - ./eth.txt:/query.txt
    command: "/bin/sh -c 'while true; do sleep 0.30; curl -sS -H \"content-type: application/json\" -d @/query.txt https://evmos-rpc.gateway.pokt.network >> output.txt; done;'"

  iot-mainnet:
    image: settler:latest
    container_name: iot-mainnet
    volumes:
      - ./eth.txt:/query.txt
    command: "/bin/sh -c 'while true; do sleep 0.30; curl -sS -H \"content-type: application/json\" -d @/query.txt https://iotex-mainnet.gateway.pokt.network/v1/613e06ce6de3a1182c7fb8e0 >> output.txt; done;'"

  harmony-mainnet:
    image: settler:latest
    container_name: harmony-0
    volumes:
      - ./hmy.txt:/query.txt
    command: "/bin/sh -c 'while true; do sleep 0.1; curl -sS -H \"content-type: application/json\" -d @/query.txt https://harmony-0.gateway.pokt.network/v1/60d2195247921f33f9d5aa68 >> output.txt; done;'"

  solana-mainnet:
    image: settler:latest
    container_name: solana-mainnet
    volumes:
      - ./sol.txt:/query.txt
    command: "/bin/sh -c 'while true; do sleep 0.1; curl -sS -H \"content-type: application/json\" -d @/query.txt https://solana-mainnet.gateway.pokt.network/v1/60d2195247921f33f9d5aa68 >> output.txt; done;'"

  solana-mainnet2:
    image: settler:latest
    container_name: solana-mainnet2
    volumes:
      - ./sol.txt:/query.txt
    command: "/bin/sh -c 'while true; do sleep 0.1; curl -sS -H \"content-type: application/json\" -d @/query.txt https://solana-mainnet.gateway.pokt.network/v1/613e06ce6de3a1182c7fb8e0 >> output.txt; done;'"

  poly-mainnet:
    image: settler:latest
    container_name: poly-mainnet
    volumes:
      - ./eth.txt:/query.txt
    command: "/bin/sh -c 'while true; do sleep 0.30; curl -sS -H \"content-type: application/json\" -d @/query.txt https://poly-mainnet.gateway.pokt.network/v1/613e06ce6de3a1182c7fb8e0 >> output.txt; done;'"

  poly-archival:
    image: settler:latest
    container_name: poly-archival
    volumes:
      - ./eth.txt:/query.txt
    command: "/bin/sh -c 'while true; do sleep 0.22; curl -sS -H \"content-type: application/json\" -d @/query.txt https://poly-archival.gateway.pokt.network/v1/60d2195247921f33f9d5aa68 >> output.txt; done;'"

  bsc-mainnet:
    image: settler:latest
    container_name: bsc-mainnet
    volumes:
      - ./eth.txt:/query.txt
    command: "/bin/sh -c 'while true; do sleep 0.28; curl -sS -H \"content-type: application/json\" -d @/query.txt https://bsc-mainnet.gateway.pokt.network/v1/613e06ce6de3a1182c7fb8e0 >> output.txt; done;'"

  fuse-archival:
    image: settler:latest
    container_name: fuse-archival
    volumes:
      - ./eth.txt:/query.txt
    command: "/bin/sh -c 'while true; do sleep 0.18; curl -sS -H \"content-type: application/json\" -d @/query.txt https://fuse-archival.gateway.pokt.network/v1/613e06ce6de3a1182c7fb8e0 >> output.txt; done;'"

  xdai-archival:
    image: settler:latest
    container_name: xdai-archival
    volumes:
      - ./eth.txt:/query.txt
    command: "/bin/sh -c 'while true; do sleep 0.23; curl -sS -H \"content-type: application/json\" -d @/query.txt https://poa-xdai-archival.gateway.pokt.network/v1/60d2195247921f33f9d5aa68 >> output.txt; done;'"

  avax-archival:
    image: settler:latest
    container_name: avax-archival
    volumes:
      - ./ava.txt:/query.txt
    command: "/bin/sh -c 'while true; do sleep 0.28; curl -sS -H \"content-type: application/json\" -d @/query.txt https://avax-archival.gateway.pokt.network/v1/613e06ce6de3a1182c7fb8e0/ext/info >> output.txt; done;'"

  avax-mainnet:
    image: settler:latest
    container_name: avax-mainnet
    volumes:
      - ./ava.txt:/query.txt
    command: "/bin/sh -c 'while true; do sleep 0.28; curl -sS -H \"content-type: application/json\" -d @/query.txt https://avax-mainnet.gateway.pokt.network/v1/613e06ce6de3a1182c7fb8e0/ext/info >> output.txt; done;'"

  eth-trace:
    image: settler:latest
    container_name: eth-trace
    volumes:
      - ./eth.txt:/query.txt
    command: "/bin/sh -c 'while true; do sleep 0.22; curl -sS -H \"content-type: application/json\" -d @/query.txt https://eth-trace.gateway.pokt.network/v1/60d2195247921f33f9d5aa68 >> output.txt; done;'"

  eth-kovan:
    image: settler:latest
    container_name: eth-kovan
    volumes:
      - ./eth.txt:/query.txt
    command: "/bin/sh -c 'while true; do sleep 0.28; curl -sS -H \"content-type: application/json\" -d @/query.txt https://poa-kovan.gateway.pokt.network/v1/60d2195247921f33f9d5aa68 >> output.txt; done;'"

  eth-ropsten:
    image: settler:latest
    container_name: eth-ropsten
    volumes:
      - ./eth.txt:/query.txt
    command: "/bin/sh -c 'while true; do sleep 0.28; curl -sS -H \"content-type: application/json\" -d @/query.txt https://eth-ropsten.gateway.pokt.network/v1/60d2195247921f33f9d5aa68 >> output.txt; done;'"

  eth-rinkeby:
    image: settler:latest
    container_name: eth-rinkeby
    volumes:
      - ./eth.txt:/query.txt
    command: "/bin/sh -c 'while true; do sleep 0.28; curl -sS -H \"content-type: application/json\" -d @/query.txt https://eth-rinkeby.gateway.pokt.network/v1/60d2195247921f33f9d5aa68 >> output.txt; done;'"

  oec-mainnet:
    image: settler:latest
    container_name: oec-mainnet
    volumes:
      - ./eth.txt:/query.txt
    command: "/bin/sh -c 'while true; do sleep 0.28; curl -sS -H \"content-type: application/json\" -d @/query.txt https://oec-mainnet.gateway.pokt.network/v1/60d2195247921f33f9d5aa68 >> output.txt; done;'"

  boba-mainnet:
    image: settler:latest
    container_name: boba-mainnet
    volumes:
      - ./eth.txt:/query.txt
    command: "/bin/sh -c 'while true; do sleep 0.28; curl -sS -H \"content-type: application/json\" -d @/query.txt https://boba-mainnet.gateway.pokt.network/v1/60d2195247921f33f9d5aa68 >> output.txt; done;'"

  avax-dfk:
    image: settler:latest
    container_name: avax-dfk
    volumes:
      - ./eth.txt:/query.txt
    command: "/bin/sh -c 'while true; do sleep 0.28; curl -sS -H \"content-type: application/json\" -d @/query.txt https://avax-dfk.gateway.pokt.network/v1/60d2195247921f33f9d5aa68/ext/bc/q2aTwKuyzgs8pynF7UXBZCU7DejbZbZ6EUyHr3JQzYgwNPUPi/rpc >> output.txt; done;'"

  fantom-mainnet:
    image: settler:latest
    container_name: fantom-mainnet
    volumes:
      - ./eth.txt:/query.txt
    command: "/bin/sh -c 'while true; do sleep 0.28; curl -sS -H \"content-type: application/json\" -d @/query.txt https://fantom-rpc.gateway.pokt.network >> output.txt; done;'"

  near-mainnet:
    image: settler:latest
    container_name: near-mainnet
    volumes:
      - ./near.txt:/query.txt
    command: "/bin/sh -c 'while true; do sleep 0.28; curl -sS -H \"content-type: application/json\" -d @/query.txt https://near-rpc.gateway.pokt.network >> output.txt; done;'"

  avax-cra:
    image: settler:latest
    container_name: avax-cra
    volumes:
      - ./eth.txt:/query.txt
    command: "/bin/sh -c 'while true; do sleep 0.28; curl -sS -H \"content-type: application/json\" -d @/query.txt https://avax-cra-rpc.gateway.pokt.network >> output.txt; done;'"

  moonbeam-mainnet:
    image: settler:latest
    container_name: moonbeam-mainnet
    volumes:
      - ./eth.txt:/query.txt
    command: "/bin/sh -c 'while true; do sleep 0.28; curl -sS -H \"content-type: application/json\" -d @/query.txt https://moonbeam-rpc.gateway.pokt.network >> output.txt; done;'"
  # moonriver-mainnet:
  #   image: settler:latest
  #   container_name: moonriver-mainnet
  #   volumes:
  #     - ./eth.txt:/query.txt
  #   command: "/bin/sh -c 'while true; do sleep 0.28; curl -sS -H \"content-type: application/json\" -d @/query.txt https://moonriver-mainnet.gateway.pokt.network/v1/60d2195247921f33f9d5aa68/ext/bc/q2aTwKuyzgs8pynF7UXBZCU7DejbZbZ6EUyHr3JQzYgwNPUPi/rpc >> output.txt; done;'"
