version: "2"

services:
  poly-mainnet:
    image: settler:latest
    container_name: poly-mainnet
    volumes:
      - ./eth.txt:/query.txt
    command: "/bin/sh -c 'while true; do sleep 0.30; curl -sS -H \"content-type: application/json\" -d @/query.txt https://poly-mainnet.gateway.pokt.network/v1/60d2195247921f33f9d5aa68 >> output.txt; done;'"

  poly-archival:
    image: settler:latest
    container_name: poly-archival
    volumes:
      - ./eth.txt:/query.txt
    command: "/bin/sh -c 'while true; do sleep 0.22; curl -sS -H \"content-type: application/json\" -d @/query.txt https://poly-archival.gateway.pokt.network/v1/60d2195247921f33f9d5aa68 >> output.txt; done;'"

  bsc-mainnet:
    image: settler:latest
    container_name: bsc-mainnet
    volumes:
      - ./eth.txt:/query.txt
    command: "/bin/sh -c 'while true; do sleep 0.28; curl -sS -H \"content-type: application/json\" -d @/query.txt https://bsc-mainnet.gateway.pokt.network/v1/60d2195247921f33f9d5aa68 >> output.txt; done;'"

  bsc-archival:
    image: settler:latest
    container_name: bsc-archival
    volumes:
      - ./eth.txt:/query.txt
    command: "/bin/sh -c 'while true; do sleep 0.22; curl -sS -H \"content-type: application/json\" -d @/query.txt https://bsc-archival.gateway.pokt.network/v1/60d2195247921f33f9d5aa68 >> output.txt; done;'"

  fuse-mainnet:
    image: settler:latest
    container_name: fuse-mainnet
    volumes:
      - ./eth.txt:/query.txt
    command: "/bin/sh -c 'while true; do sleep 0.23; curl -sS -H \"content-type: application/json\" -d @/query.txt https://fuse-mainnet.gateway.pokt.network/v1/60d2195247921f33f9d5aa68 >> output.txt; done;'"

  fuse-archival:
    image: settler:latest
    container_name: fuse-archival
    volumes:
      - ./eth.txt:/query.txt
    command: "/bin/sh -c 'while true; do sleep 0.18; curl -sS -H \"content-type: application/json\" -d @/query.txt https://fuse-archival.gateway.pokt.network/v1/60d2195247921f33f9d5aa68 >> output.txt; done;'"

  xdai-archival:
    image: settler:latest
    container_name: xdai-archival
    volumes:
      - ./eth.txt:/query.txt
    command: "/bin/sh -c 'while true; do sleep 0.23; curl -sS -H \"content-type: application/json\" -d @/query.txt https://poa-xdai-archival.gateway.pokt.network/v1/60d2195247921f33f9d5aa68 >> output.txt; done;'"

  avax-mainnet:
    image: settler:latest
    container_name: avax-mainnet
    volumes:
      - ./ava.txt:/query.txt
    command: "/bin/sh -c 'while true; do sleep 0.28; curl -sS -H \"content-type: application/json\" -d @/query.txt https://avax-mainnet.gateway.pokt.network/v1/60d2195247921f33f9d5aa68/ext/info >> output.txt; done;'"

  eth-trace:
    image: settler:latest
    container_name: eth-trace
    volumes:
      - ./eth.txt:/query.txt
    command: "/bin/sh -c 'while true; do sleep 0.22; curl -sS -H \"content-type: application/json\" -d @/query.txt https://eth-trace.gateway.pokt.network/v1/60d2195247921f33f9d5aa68 >> output.txt; done;'"

  eth-kovan:
    image: settler:latest
    container_name: eth-kovan
    volumes:
      - ./eth.txt:/query.txt
    command: "/bin/sh -c 'while true; do sleep 0.28; curl -sS -H \"content-type: application/json\" -d @/query.txt https://eth-kovan.gateway.pokt.network/v1/60d2195247921f33f9d5aa68 >> output.txt; done;'"

  eth-ropsten:
    image: settler:latest
    container_name: eth-ropsten
    volumes:
      - ./eth.txt:/query.txt
    command: "/bin/sh -c 'while true; do sleep 0.28; curl -sS -H \"content-type: application/json\" -d @/query.txt https://eth-ropsten.gateway.pokt.network/v1/60d2195247921f33f9d5aa68 >> output.txt; done;'"

  eth-rinkeby:
    image: settler:latest
    container_name: eth-rinkeby
    volumes:
      - ./eth.txt:/query.txt
    command: "/bin/sh -c 'while true; do sleep 0.28; curl -sS -H \"content-type: application/json\" -d @/query.txt https://eth-rinkeby.gateway.pokt.network/v1/60d2195247921f33f9d5aa68 >> output.txt; done;'"

  eth-goerli:
    image: settler:latest
    container_name: eth-goerli
    volumes:
      - ./eth.txt:/query.txt
    command: "/bin/sh -c 'while true; do sleep 0.28; curl -sS -H \"content-type: application/json\" -d @/query.txt https://eth-goerli.gateway.pokt.network/v1/60d2195247921f33f9d5aa68 >> output.txt; done;'"




